"""empty message

Revision ID: 2c6e3d55afa8
Revises: ef56aad12df8
Create Date: 2023-11-03 20:12:47.664323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6e3d55afa8'
down_revision = 'ef56aad12df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school_user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('school_user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
